/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.auctionsobserver.Graphics;

import com.mycompany.auctionsobserver.Auction;
import com.mycompany.auctionsobserver.Observable;
import com.mycompany.auctionsobserver.Person;
import com.mycompany.auctionsobserver.Product;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Fabo
 */
public class Client extends javax.swing.JFrame implements Observable {

    /**
     * Creates new form GUI
     */
    public Client() {
        initComponents();
        
        try {
            socket = new Socket("localhost", 1234);
            inputStream = new ObjectInputStream(socket.getInputStream());
            outputStream = new ObjectOutputStream(socket.getOutputStream());
            
            new Thread(new ClientHandler()).start();
        } catch (IOException e){
            e.printStackTrace();         
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        auctionPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addAuctionButton = new javax.swing.JButton();
        auctionManagerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout auctionPanelLayout = new javax.swing.GroupLayout(auctionPanel);
        auctionPanel.setLayout(auctionPanelLayout);
        auctionPanelLayout.setHorizontalGroup(
            auctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        auctionPanelLayout.setVerticalGroup(
            auctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Auction manager");

        addAuctionButton.setText("Add an auction");
        addAuctionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAuctionButtonActionPerformed(evt);
            }
        });

        auctionManagerButton.setText("Manage your auctions");
        auctionManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auctionManagerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(auctionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(196, 196, 196)
                        .addComponent(addAuctionButton)
                        .addGap(18, 18, 18)
                        .addComponent(auctionManagerButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addAuctionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(auctionManagerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(auctionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addAuctionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAuctionButtonActionPerformed
        String name = JOptionPane.showInputDialog("Type the name of the product");
        int startPrice = Integer.parseInt(JOptionPane.showInputDialog("Type the price of the product"));
        
        Product product = new Product(name, startPrice, startPrice);
        
        selfAuctions.add(new Auction(currentClient, product));   
               
        try {
            outputStream.writeInt(ADD_AN_AUCTION);
            outputStream.writeObject(currentClient);
            outputStream.writeObject(product);
            outputStream.writeObject(new Auction(currentClient, product));
            outputStream.flush();
        } catch (IOException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addAuctionButtonActionPerformed

    private void auctionManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auctionManagerButtonActionPerformed
        
    }//GEN-LAST:event_auctionManagerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                String userName = JOptionPane.showInputDialog(null, "Ingrese su nombre:");
                               
                Client gui = new Client();
                gui.setTitle(userName);
                gui.setVisible(true);
                currentClient.setName(userName);
                auctionPanel.setLayout(new BoxLayout(auctionPanel, BoxLayout.Y_AXIS));
                
            }
        });
    }

    @Override
    public void auctionWon(Auction auction) {
        currentClient.update(auction);
    }
    
    
    private class ClientHandler implements Runnable {
        @Override
        public void run() {
            try {
                while (true) {
                    int option = inputStream.readInt();
                    
                    switch (option){
                        
                        case (ADD_AN_AUCTION) -> {
                            Person auctioneer = (Person)inputStream.readObject();
                            Product product = (Product)inputStream.readObject();
                            Auction auction = (Auction)inputStream.readObject();
                            
                            generalAuctions.add(auction);
                            
                            JButton auctionButton = new JButton();
                            auctionButton.setText("Auctioneer: " + auctioneer.getName() + ". Product name: " + product.getName() + ". Price: " + product.getStartPrice());
                            auctionButton.putClientProperty("productName", product.getName());
                            auctionButton.putClientProperty("Owner", auctioneer.getName());
                            auctionButton.putClientProperty("Status", "IN PROGRESS");
                            auctionButton.putClientProperty("Top Bidder", "none");
                            auctionButton.putClientProperty("Price", product.getStartPrice());
                            
                            auctionButton.addActionListener(new ActionListener() {
                                @Override
                                public void actionPerformed(ActionEvent e){
                                    String owner = (String) auctionButton.getClientProperty("Owner");
                                    String productName = (String) auctionButton.getClientProperty("productName");
                                    String topBidder = (String) auctionButton.getClientProperty("Top Bidder");
                                    int price = (int) auctionButton.getClientProperty("Price");
                                    
                                    try {
                                        if (auctionButton.getClientProperty("Status").equals("ENDED")){
                                            JOptionPane.showMessageDialog(null, "This auction has ended");
                                        } else if (auctionButton.getClientProperty("Status").equals("CANCELED")){
                                            JOptionPane.showMessageDialog(null, "This auction has been canceled");
                                            
                                        } else {
                                        
                                            if (owner.equals(currentClient.getName())){
                                                UIManager.put("OptionPane.yesButtonText", "End auction");
                                                UIManager.put("OptionPane.noButtonText", "Cancel auction");
                                                
                                                
                                                int option = JOptionPane.showConfirmDialog(null,
                                                        "End this auction?", "Confirmation", JOptionPane.YES_NO_OPTION);

                                                if (option == JOptionPane.YES_OPTION){                                              
                                                    outputStream.writeInt(AUCTION_END);
                                                    outputStream.writeUTF(productName);
                                                    outputStream.writeUTF("ENDED");
                                                    outputStream.writeObject(auction);
                                                    outputStream.writeUTF(topBidder);
                                                    outputStream.writeInt(price);
                                                    outputStream.flush();
                                                } else {
                                                    outputStream.writeInt(AUCTION_CANCELED);
                                                    outputStream.writeUTF(productName);
                                                    outputStream.writeUTF("CANCELED");
                                                    outputStream.writeObject(auction);
                                                    outputStream.writeInt(price);
                                                    outputStream.flush();
                                                }
                                            } else {

                                                int newPrice = Integer.parseInt(JOptionPane.showInputDialog("Enter your bid:"));

                                                if (newPrice > price){
                                                    product.setStartPrice(newPrice);
                                                    auctionButton.putClientProperty("Price", newPrice);
                                                    auction.setTopBidder(currentClient);

                                                    auctionButton.setText("Auctioneer: " + auctioneer.getName() + ". Product name: " +
                                                            product.getName() + ". Price: " + newPrice);

                                                    outputStream.writeInt(BID_FOR_AN_AUCTION);
                                                    outputStream.writeInt(newPrice);
                                                    outputStream.writeObject(currentClient);
                                                    outputStream.writeObject(product);
                                                    outputStream.writeObject(auction);
                                                    outputStream.writeObject(auctioneer);
                                                    outputStream.writeUTF(productName);
                                                    outputStream.flush();   

                                                    } else {
                                                    JOptionPane.showMessageDialog(null, "Bid must be higher than the actual bid");
                                                }
                                            }
                                        
                                        } 
                                    } catch (IOException ex) {
                                        Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                }                         
                            });
                            auctionPanel.add(auctionButton);
                            auctionPanel.revalidate();
                            auctionPanel.repaint();
                        }
                            
                        case (BID_FOR_AN_AUCTION) -> {
                            
                            Product prod = (Product)inputStream.readObject();
                            Person bidder = (Person)inputStream.readObject();
                            Auction auctionBidded = (Auction)inputStream.readObject();
                            Person auctionOwner = (Person)inputStream.readObject();
                            int price = inputStream.readInt();
                            String pKey = inputStream.readUTF();                           
                                                       
                            prod.setStartPrice(price);
                            auctionBidded.setTopBidder(bidder);

                            for (Component comp : auctionPanel.getComponents()){

                                JButton button = (JButton) comp;
                                String buttonProductName = (String) button.getClientProperty("productName");

                                if (buttonProductName.equals(pKey)) {
                                    button.setText("Auctioneer: " + auctionOwner.getName() + ". Product name: " + prod.getName() + ". Price: " + price);
                                    button.putClientProperty("Top Bidder", bidder.getName());

                                    break;  
                                }                               
                            }                    
                        }
                        
                        case (AUCTION_END) -> {
                            
                            String pKey = inputStream.readUTF();
                            String status = inputStream.readUTF();
                            Auction auction = (Auction)inputStream.readObject();
                            String winner = inputStream.readUTF();
                            int price = inputStream.readInt();
                            
                            for (Component comp : auctionPanel.getComponents()){

                                JButton button = (JButton) comp;
                                String buttonProductName = (String) button.getClientProperty("productName");
                                String topBidder = (String) button.getClientProperty("Top Bidder");

                                if (buttonProductName.equals(pKey)) {
                                    button.putClientProperty("Status", status);
                                    button.setText("Auctioneer: " + auction.getAuctioneerName() + ". Product name: " + auction.getAuctionProductName() + ". Price: " + price
                                    + " Winner: " + topBidder);
                                    break;  
                                }
                                if (currentClient.getName().equals(winner)){
                                    auctionWon(auction);
                                }
                            }       
                        }
                        
                        case (AUCTION_CANCELED) -> {
                            String pKey = inputStream.readUTF();
                            String status = inputStream.readUTF();
                            Auction auction = (Auction)inputStream.readObject();
                            int price = inputStream.readInt();
                            
                            for (Component comp : auctionPanel.getComponents()){
                                JButton button = (JButton) comp;
                                String buttonProductName = (String) button.getClientProperty("productName");
                                
                                if (buttonProductName.equals(pKey)) {
                                    button.putClientProperty("Status", status);
                                    button.setText("Auctioneer: " + auction.getAuctioneerName() + ". Product name: " + auction.getAuctionProductName() + ". Price: " + price
                                    + " " + status);
                                    break;  
                                }
                            }
                        }
                    }
                }
            } catch (IOException e) {
                e.printStackTrace();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

   
    private ArrayList<Auction> generalAuctions = new ArrayList<>(); //this will be broadcasted through all the sockets!
    private ArrayList<Auction> selfAuctions = new ArrayList<>();
    private static Person currentClient = new Person("");
    
    private final static int ADD_AN_AUCTION = 1;
    private final static int BID_FOR_AN_AUCTION = 2;
    private final static int AUCTION_END = 3;
    private final static int AUCTION_CANCELED = 4;
    
    private ObjectOutputStream outputStream;
    private ObjectInputStream inputStream;
    private Socket socket;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAuctionButton;
    private javax.swing.JButton auctionManagerButton;
    private static javax.swing.JPanel auctionPanel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}